### ISSUE TITLE
鸡哥会在vim里头跳舞，挡住第一列

### ISSUE THREAD

**Issue by ebnOs0** [AmyangXYZ/zhiyin-zsh-theme#1]
![image](https://user-images.githubusercontent.com/49959636/234766656-e3172a03-ddc5-4fda-b496-c234f59ee8d4.png)

有没有可以配置theme的方法解决这个问题呀

**Comment by AmyangXYZ** [comment]
没想到什么好办法在theme里判断是否进入了vim，不过你可以把下面这段代码放到你的.zshrc里。

```shell
enter_vim() {
  psanimate_stop
  vim "$@"
  psanimate 0.08
}
alias vim="enter_vim"
```

可以创建类似alias的来绕过你觉得坤坤挡住你的地方（但你就不是真正的ikun了

**Comment by AmyangXYZ** [comment]
https://github.com/AmyangXYZ/zhiyin-zsh-theme/issues/2#issue-1695484428

**Comment by ebnOs0** [comment]
> 没想到什么好办法在theme里判断是否进入了vim，不过你可以把下面这段代码放到你的.zshrc里。
> 
> ```shell
> enter_vim() {
>   psanimate_stop
>   vim "$@"
>   psanimate 0.08
> }
> alias vim="enter_vim"
> ```
> 
> 可以创建类似alias的来绕过你觉得坤坤挡住你的地方（但你就不是真正的ikun了

好的好的，我去试试，才看到回复，鸡门🤝
