### ISSUE TITLE
iTerm2升级后无法使用

### ISSUE THREAD

**Issue by GengJian** [AmyangXYZ/zhiyin-zsh-theme#4]
<img width="334" alt="image" src="https://github.com/AmyangXYZ/zhiyin-zsh-theme/assets/13254245/2e3ac768-6539-4e6d-87a5-df2a058f8be1">

**Comment by AmyangXYZ** [comment]
我这里还是可以的，检查下zhiyin字体有没有设置好？
<img width="696" alt="Screenshot 2024-05-27 at 16 28 15" src="https://github.com/AmyangXYZ/zhiyin-zsh-theme/assets/23499774/969a6c0e-646c-4ba0-9b5d-b96a0a2d306a">

**Comment by GengJian** [comment]
同3.5.0版本，主题用的robbyrussell.zsh-theme 之前就加了示例代码块

之前好好的，就是升级了iterm之后提示报错

字体用的zhiyin
![Uploading image.png…]()

**Comment by GengJian** [comment]
<img width="260" alt="image" src="https://github.com/AmyangXYZ/zhiyin-zsh-theme/assets/13254245/dc00fd0f-42c4-41f2-86df-4c0bcdf5a587">

又有了新的提示，是不是和locale有关
